openapi: 3.0.3
info:
  title: Organizations API
  version: 1.0.0
  description: API для работы с организациями и зданиями

servers:
  - url: http://localhost:8080/api

# глобально включаем авторизацию
security:
  - ApiKeyAuth: []

paths:
  # 1. Список организаций в конкретном здании
  /organizations/building/{buildingId}:
    get:
      summary: "Список организаций в конкретном здании"
      parameters:
        - name: buildingId
          in: path
          required: true
          schema:
            type: integer
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

  # 2. Список организаций по виду деятельности
  /organizations/activity/{activityId}:
    get:
      summary: "Список организаций по виду деятельности"
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

  # 3a. Список организаций в радиусе
  /organizations/radius:
    get:
      summary: "Список организаций в радиусе"
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: radius
          in: query
          required: false
          schema:
            type: number
            default: 5
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

  # 3b. Список организаций в прямоугольной области
  /organizations/bybbox:
    get:
      summary: "Список организаций в прямоугольной области (bbox)"
      parameters:
        - name: lat1
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: lng1
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: lat2
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: lng2
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

  # 4. Информация об организации по ID
  /organizations/{id}:
    get:
      summary: "Информация об организации"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Детальная информация об организации"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'

  # 5. Поиск организаций по виду деятельности с вложенностью
  /organizations/search-by-activity:
    get:
      summary: "Поиск организаций по виду деятельности с вложенностью"
      parameters:
        - name: activityName
          in: query
          required: true
          schema:
            type: string
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

  # 6. Поиск организаций по названию
  /organizations/search:
    get:
      summary: "Поиск организаций по названию"
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: "Список организаций"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizations'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phones:
          type: array
          items:
            type: string
        building:
          $ref: '#/components/schemas/Building'
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    Building:
      type: object
      properties:
        id:
          type: integer
        address:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float

    Activity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        parent_id:
          type: integer
          nullable: true

    PaginatedOrganizations:
      type: object
      properties:
        current_page:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
        per_page:
          type: integer
        total:
          type: integer
