openapi: 3.0.3
info:
  title: Organizations API
  version: 1.0.0
  description: API для поиска организаций по радиусу и получения информации о зданиях и видах деятельности
servers:
  - url: http://localhost:8080
    description: Локальный сервер

paths:
  /api/organizations:
    get:
      summary: Получить список организаций в радиусе
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Широта точки
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Долгота точки
        - name: radius
          in: query
          required: false
          schema:
            type: number
            format: float
            default: 5
          description: Радиус поиска в км
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Количество организаций на странице
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Номер страницы
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Organization'
                  per_page:
                    type: integer
                  total:
                    type: integer
        '401':
          description: Не авторизован (неверный API-ключ)
        '422':
          description: Ошибка валидации параметров

components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phones:
          type: array
          items:
            type: string
        building_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        building:
          $ref: '#/components/schemas/Building'
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    Building:
      type: object
      properties:
        id:
          type: integer
        address:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Activity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        parent_id:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
